name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
